name: tactful-tom
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - attrs=24.3.0=py310h06a4308_0
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=12.8=3
  - distro=1.9.0=pyhd8ed1ab_1
  - filelock=3.17.0=py310h06a4308_0
  - fsspec=2024.12.0=py310h06a4308_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py310h5eee18b_0
  - huggingface_hub=0.29.2=py310h06a4308_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.6=py310h06a4308_0
  - joblib=1.4.2=py310h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.13.1.3=0
  - libcurand=10.3.9.90=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=14.2.0=h767d61c_2
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py310hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - networkx=3.2.1=py310h06a4308_0
  - numpy=1.22.3=py310hfa59a62_0
  - numpy-base=1.22.3=py310h9585f30_0
  - openssl=3.5.0=h7b32b05_0
  - packaging=24.2=py310h06a4308_0
  - pip=25.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.16=he870216_1
  - pytorch=2.5.1=py3.10_cpu_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cpu
  - pytz=2024.1=py310h06a4308_0
  - pyyaml=6.0.2=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_1
  - scikit-learn=1.6.1=py310h6a678d5_0
  - scipy=1.7.3=py310hfa59a62_0
  - setuptools=75.8.0=py310h06a4308_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.3=py310h06a4308_1
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py310h2f386ee_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.5.1=py310_cpu
  - tqdm=4.67.1=py310h2f386ee_0
  - typing-extensions=4.12.2=py310h06a4308_0
  - typing_extensions=4.12.2=py310h06a4308_0
  - tzdata=2025a=h04d1e81_0
  - urllib3=2.3.0=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
prefix: /home/jiahao_huang/anaconda3/envs/fraud
